services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    hostname: cassandra1
    ports:
      - 9042:9042
    networks:
      cassandranet:
        ipv4_address: 172.24.0.2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      - CASSANDRA_DATACENTER=dc1

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    hostname: cassandra2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
      - CASSANDRA_DATACENTER=dc1
    depends_on:
      cassandra1:
        condition: service_started
    networks:
      cassandranet:
        ipv4_address: 172.24.0.3

networks:
  cassandranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16

