spring.data.mongodb.uri=mongodb://admin:admin123@mongodb1:27017,mongodb2:27018,mongodb3:27019/nbd?replicaSet=replica_set_single&authSource=admin
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.ddl-auto=drop-and-create
spring.data.mongodb.uuid-representation=standard
server.address=0.0.0.0
server.port=8080
jwt.secret=TwojTajnyKluczDlaJWTKtoryMaMinimum32Znaki
jwt.expiration=86400000
jws.secret=InnyTajnyKluczDlaJWSDoPodpisywaniaIDZasobow
